package com.drmangotea.tfmg.content.engines.engine_controller.packets;

import com.drmangotea.tfmg.content.engines.engine_controller.EngineControllerBlockEntity;
import net.minecraft.core.BlockPos;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.server.level.ServerPlayer;


//public class EngineControllerBindPacket extends EngineControllerPacketBase {
//
//	private int button;
//	private BlockPos linkLocation;
//
//	public EngineControllerBindPacket(int button, BlockPos linkLocation) {
//		super((BlockPos) null);
//		this.button = button;
//		this.linkLocation = linkLocation;
//	}
//
//	public EngineControllerBindPacket(FriendlyByteBuf buffer) {
//		super(buffer);
//		this.button = buffer.readVarInt();
//		this.linkLocation = buffer.readBlockPos();
//	}
//
//	@Override
//	public void write(FriendlyByteBuf buffer) {
//		super.write(buffer);
//		buffer.writeVarInt(button);
//		buffer.writeBlockPos(linkLocation);
//	}
//
//
//
//	@Override
//	protected void handleController(ServerPlayer player, EngineControllerBlockEntity lectern) {}
//
//}
